version: 2

models:
  - name: int_session_events_agg
    columns:
      - name: session_id 
        description: This is an unique identifier for the session
        test: 
          - not_null
          - unique
      - name: session_length_min
        test:
          - non_negative